### ISSUE TITLE
Live Site - "Jupiter Broadcasting" goes to the LAS SubReddit

### ISSUE THREAD

**Issue by mattburchett** [rikai/JupiterColony.com#2]
Noticed when browsing through the code that the Jupiter Broadcasting link for the live website leads to the LAS subreddit. Wasn't sure if this was intentional, or actually meant to go to http://jupiterbroadcasting.com

-- Matt
(themattbeballin in IRC)

**Comment by rikai** [comment]
Fixed. :)
